//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab7
{
    using System;
    using System.Collections.Generic;
    
    public partial class WritingDisability
    {
        public int ID { get; set; }
        public string DataStart { get; set; }
        public string DataFinish { get; set; }
        public string Result { get; set; }
        public int Patient { get; set; }
        public int Doctor { get; set; }
    
        public virtual Doctor Doctor1 { get; set; }
        public virtual Patient Patient1 { get; set; }
    }
}
